"""Add event_vendors association table

Revision ID: 477643737aad
Revises: 8c91fb505862
Create Date: 2024-10-27 07:44:16.862021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477643737aad'
down_revision = '8c91fb505862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_vendors',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.vendor_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_vendors')
    # ### end Alembic commands ###
