"""Initial migration after reset

Revision ID: 8c91fb505862
Revises: 
Create Date: 2024-10-27 06:36:44.110002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c91fb505862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_picture', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Vendor',
    sa.Column('vendor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('service_fee', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('Event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4082), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('spent_budget', sa.Float(), nullable=False),
    sa.Column('expenses', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('Reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('Guest',
    sa.Column('guest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_table('Task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('event_vendor',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'vendor_id')
    )
    op.create_table('Invitation',
    sa.Column('invitation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['Guest.guest_id'], ),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Invitation')
    op.drop_table('event_vendor')
    op.drop_table('Task')
    op.drop_table('Guest')
    op.drop_table('Reviews')
    op.drop_table('Event')
    op.drop_table('Vendor')
    op.drop_table('User')
    # ### end Alembic commands ###
