"""Inset status, spent_budget amd expenses attributes as not nullable

Revision ID: 92fdf5a5829f
Revises: bd4ccbb91e04
Create Date: 2024-10-26 15:13:56.687918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '92fdf5a5829f'
down_revision = 'bd4ccbb91e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('spent_budget',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('expenses',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.alter_column('expenses',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('spent_budget',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    # ### end Alembic commands ###
