"""remove unique constraint in event_vendors association table

Revision ID: db9e8762dbb1
Revises: 9e61314473ad
Create Date: 2024-10-31 16:07:24.700121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9e8762dbb1'
down_revision = '9e61314473ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_vendors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_event_vendors', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_vendors', ['event_id', 'vendor_id'])

    # ### end Alembic commands ###
