"""create event vendor table

Revision ID: e021fdb3b090
Revises: 88ddeeed47c0
Create Date: 2024-10-31 15:12:23.337923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e021fdb3b090'
down_revision = '88ddeeed47c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_vendor',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'vendor_id'),
    sa.UniqueConstraint('event_id', 'vendor_id', name='uq_event_vendor')
    )
    op.create_table('event_vendors',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.event_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.vendor_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_vendors')
    op.drop_table('event_vendor')
    # ### end Alembic commands ###
